### ISSUE TITLE
ASOS_DEBUG command yielding error

### ISSUE THREAD

**Issue by thalesmello** [fcpg/tmux-asos#1]
When I run the command, the following line prints out

```
'[[ ! -v ASOS_DEBUG ]] && rm /tmp/{asos.{in,out,allpanes},compword.out} || true' returned 2
```

**Comment by fcpg** [comment]
Hello,

What OS and shell do you use? Could you post the output of the command `shopt`?
Do you still have the error if you set the ASOS_DEBUG variable ie. `export ASOS_DEBUG=1` ?

**Comment by veelenga** [comment]
@fcpg i have the same error. I'm on iOS + zsh. There is no debug information after i export ASOS_DEBUG and it does not fix the problem 😢 

Once i change [this line](https://github.com/fcpg/tmux-asos/blob/master/asos.tmux#L27) from

``` sh
run-shell    "[[ ! -v ASOS_DEBUG ]] && rm ${ASOS_TMPDIR:-/tmp}/{asos.{in,out,allpanes},compword.out} || true"
```

to 

``` sh
run-shell    "rm ${ASOS_TMPDIR:-/tmp}/{asos.{in,out,allpanes},compword.out} || true"
```

and reloaded the env, it starts to work for me.

**Comment by fcpg** [comment]
zsh probably chokes on the bashism. I removed that part, it should work properly now.

Thanks for the feedback -- let me know if it's good, so that I can close the issue.

**Comment by veelenga** [comment]
@fcpg yup, that fixed the problem on my side. Thanks
